
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.jbrod.calculadoracompi.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 9;
  public static final int SUMA = 5;
  public static final int MULTIPLICACION = 3;
  public static final int EOF = 0;
  public static final int NUMERO = 2;
  public static final int error = 1;
  public static final int DIVISION = 4;
  public static final int PARC = 8;
  public static final int RESTA = 6;
  public static final int PARA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "MULTIPLICACION",
  "DIVISION",
  "SUMA",
  "RESTA",
  "PARA",
  "PARC",
  "COMA"
  };
}

